apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: loginapp
spec:
  params:
    - name: BUILDER_IMAGE
      description: The image on which builds will run
      default: loginapp:latest
  resources:
    - name: source
      type: git
  tasks:
    - name: build
      taskRef:
        name: build-docker
      params:
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
      resources:
        inputs:
          - name: source
            resource: source
